/**
 * Full build script that creates a complete dist/ folder for deployment
 *
 * Usage: npm run build
 *
 * This script:
 * 1. Cleans dist/ folder
 * 2. Copies static files (html, css, js, etc.)
 * 3. Optimizes images (converts jpg/png to webp)
 * 4. Builds events from YAML → events.js + events.json
 * 5. Generates event detail pages
 * 6. Generates sitemap.xml
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const sharp = require('sharp');

const ROOT_DIR = path.join(__dirname, '..');
const SRC_DIR = path.join(ROOT_DIR, 'src');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const EVENTS_SOURCE = path.join(SRC_DIR, 'events');

// Load shared constants
const constants = require('../src/data/constants.json');
const SITE_URL = constants.SITE_URL;
const categoryLabels = constants.CATEGORY_LABELS;
const MONTHS_FULL = constants.MONTHS_FULL;

// Static files and folders to copy
const STATIC_FILES = [
    'index.html',
    'all-events.html',
    'other-clubs.html',
    'robots.txt',
    'llms.txt',
    'CNAME',
    'ics-browserified.js'
];

const STATIC_FOLDERS = [
    'js',
    'data',
    'ThankYouPage'
];

// Note: CSS is generated by Tailwind CLI after this script runs

// Image optimization settings
const WEBP_QUALITY = 80;
const EXTENSIONS_TO_CONVERT = ['.jpg', '.jpeg', '.png'];
const EXTENSIONS_TO_COPY = ['.svg', '.webp', '.gif', '.ico'];

/**
 * Recursively copy a directory
 */
function copyDir(src, dest) {
    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }

    const entries = fs.readdirSync(src, { withFileTypes: true });

    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);

        if (entry.isDirectory()) {
            copyDir(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

/**
 * Optimize and copy images to dist
 */
async function optimizeImages() {
    console.log('Optimizing images...');

    const srcImgDir = path.join(SRC_DIR, 'img');
    const destImgDir = path.join(DIST_DIR, 'img');

    if (!fs.existsSync(srcImgDir)) {
        console.log('  No img/ folder found\n');
        return;
    }

    fs.mkdirSync(destImgDir, { recursive: true });

    const files = fs.readdirSync(srcImgDir);
    let converted = 0;
    let copied = 0;
    let totalSaved = 0;

    for (const file of files) {
        const ext = path.extname(file).toLowerCase();
        const srcPath = path.join(srcImgDir, file);
        const stat = fs.statSync(srcPath);

        if (stat.isDirectory()) {
            // Recursively copy subdirectories
            copyDir(srcPath, path.join(destImgDir, file));
            console.log(`  ✓ ${file}/ (copied)`);
            continue;
        }

        if (EXTENSIONS_TO_CONVERT.includes(ext)) {
            // Convert to WebP
            const nameWithoutExt = path.basename(file, ext);
            const destPath = path.join(destImgDir, `${nameWithoutExt}.webp`);

            const inputSize = stat.size;
            await sharp(srcPath)
                .webp({ quality: WEBP_QUALITY })
                .toFile(destPath);

            const outputSize = fs.statSync(destPath).size;
            const savings = ((1 - outputSize / inputSize) * 100).toFixed(0);
            totalSaved += inputSize - outputSize;

            console.log(`  ✓ ${file} → ${nameWithoutExt}.webp (-${savings}%)`);
            converted++;
        } else if (EXTENSIONS_TO_COPY.includes(ext)) {
            // Copy as-is
            fs.copyFileSync(srcPath, path.join(destImgDir, file));
            console.log(`  ✓ ${file}`);
            copied++;
        }
    }

    console.log(`\n  Converted: ${converted}, Copied: ${copied}, Saved: ${(totalSaved / 1024).toFixed(0)}KB\n`);
}

/**
 * Clean and create dist directory
 */
function cleanDist() {
    console.log('Cleaning dist/...');
    if (fs.existsSync(DIST_DIR)) {
        fs.rmSync(DIST_DIR, { recursive: true });
    }
    fs.mkdirSync(DIST_DIR, { recursive: true });
    console.log('✓ dist/ cleaned\n');
}

/**
 * Copy static files to dist
 */
function copyStaticFiles() {
    console.log('Copying static files from src/...');

    // Copy individual files from src/
    for (const file of STATIC_FILES) {
        const src = path.join(SRC_DIR, file);
        const dest = path.join(DIST_DIR, file);
        if (fs.existsSync(src)) {
            fs.copyFileSync(src, dest);
            console.log(`  ✓ ${file}`);
        }
    }

    // Copy folders from src/
    for (const folder of STATIC_FOLDERS) {
        const src = path.join(SRC_DIR, folder);
        const dest = path.join(DIST_DIR, folder);
        if (fs.existsSync(src)) {
            copyDir(src, dest);
            console.log(`  ✓ ${folder}/`);
        }
    }

    // Create css folder for Tailwind output
    const cssDir = path.join(DIST_DIR, 'css');
    if (!fs.existsSync(cssDir)) {
        fs.mkdirSync(cssDir, { recursive: true });
        console.log('  ✓ css/ (created for Tailwind)');
    }

    console.log('');
}

/**
 * Build events from YAML files
 */
function buildEvents() {
    console.log('Building events from YAML...');

    const files = fs.readdirSync(EVENTS_SOURCE)
        .filter(f => f.endsWith('.yaml') || f.endsWith('.yml'))
        .sort()
        .reverse();

    const events = [];

    for (const file of files) {
        const filePath = path.join(EVENTS_SOURCE, file);
        const content = fs.readFileSync(filePath, 'utf8');

        try {
            const event = yaml.load(content);
            if (event.description) {
                event.description = event.description.trim();
            }
            if (event.ticketLink && !event.googleFormLink) {
                event.googleFormLink = event.ticketLink;
            }
            events.push(event);
            console.log(`  ✓ ${file}`);
        } catch (err) {
            console.error(`  ✗ ${file}: ${err.message}`);
        }
    }

    // Sort events
    events.sort((a, b) => {
        if (a.isFavorite && !b.isFavorite) return -1;
        if (!a.isFavorite && b.isFavorite) return 1;
        return new Date(b.date) - new Date(a.date);
    });

    // Write events.js
    const jsContent = `// Auto-generated from YAML files
// Run 'npm run build:dist' to regenerate

const events = ${JSON.stringify(events, null, 2)};

export default events;
`;
    const jsPath = path.join(DIST_DIR, 'js', 'events.js');
    fs.writeFileSync(jsPath, jsContent, 'utf8');
    console.log(`\n  ✓ js/events.js`);

    // Write events.json
    const jsonPath = path.join(DIST_DIR, 'data', 'events.json');
    fs.writeFileSync(jsonPath, JSON.stringify(events, null, 2), 'utf8');
    console.log(`  ✓ data/events.json`);

    console.log(`\nTotal: ${events.length} events\n`);
    return events;
}

/**
 * Format date helpers
 */
function formatDate(dateString) {
    const date = new Date(dateString);
    return `${date.getDate()} ${MONTHS_FULL[date.getMonth()]} ${date.getFullYear()}`;
}

function formatDateISO(dateString, time) {
    return `${dateString}T${time}:00`;
}

function stripHtml(html) {
    return (html || '').replace(/<[^>]*>/g, '').replace(/\n/g, ' ').trim().substring(0, 200);
}

/**
 * Get day of week in Ukrainian
 */
function getDayOfWeek(dateString) {
    const days = ['Неділя', 'Понеділок', 'Вівторок', 'Середа', 'Четвер', "П'ятниця", 'Субота'];
    const date = new Date(dateString);
    return days[date.getDay()];
}

/**
 * Pre-render hero section in index.html with the featured event
 */
function preRenderHeroSection(events) {
    console.log('Pre-rendering hero section...');

    const now = new Date();

    // Get upcoming events (same logic as app.js)
    const upcomingEvents = events
        .filter(e => new Date(`${e.date}T${e.time}`) >= now)
        .sort((a, b) => new Date(a.date) - new Date(b.date));

    if (upcomingEvents.length === 0) {
        console.log('  No upcoming events, skipping hero pre-render\n');
        return;
    }

    // Find hero event (same logic as app.js displayHeroEvent)
    const heroEvent = upcomingEvents.find(e => e.isFavorite && e.image)
        || upcomingEvents.find(e => e.image)
        || upcomingEvents[0];

    if (!heroEvent || !heroEvent.image) {
        console.log('  No hero event with image found, skipping\n');
        return;
    }

    const imageSrc = heroEvent.image.startsWith('/') ? heroEvent.image : `/${heroEvent.image}`;
    const categoryLabel = categoryLabels[heroEvent.category] || 'Подія';
    const dateFormatted = `${getDayOfWeek(heroEvent.date)}, ${formatDate(heroEvent.date)}`;
    const description = stripHtml(heroEvent.description || '').substring(0, 200) + '...';

    // Build actions HTML
    let actionsHtml = '';
    if (heroEvent.ticketLink || heroEvent.googleFormLink) {
        actionsHtml += `<a href="${heroEvent.ticketLink || heroEvent.googleFormLink}" target="_blank" class="btn btn-primary">Придбати квитки</a>`;
    }
    actionsHtml += `<a href="/events/${heroEvent.id}/" class="btn btn-outline-light">Дізнатися більше</a>`;

    // Location HTML
    let locationHtml = heroEvent.location;
    if (heroEvent.linkToMaps) {
        locationHtml = `<a href="${heroEvent.linkToMaps}" target="_blank" rel="noopener" style="color: white;">${heroEvent.location}</a>`;
    }

    // Read index.html from dist
    const indexPath = path.join(DIST_DIR, 'index.html');
    let html = fs.readFileSync(indexPath, 'utf8');

    // Add preload link for hero image (before </head>)
    const preloadLink = `<link rel="preload" href="${imageSrc}" as="image" fetchpriority="high">\n</head>`;
    html = html.replace('</head>', preloadLink);

    // Replace hero section (remove display:none and populate content)
    const heroSectionRegex = /<section class="hero-event" id="hero-event" style="display: none;">[\s\S]*?<\/section>\s*<!-- Filter/;

    const preRenderedHero = `<section class="hero-event" id="hero-event">
            <div class="container">
                <div class="hero-event__inner">
                    <div class="hero-event__image">
                        <img id="hero-event-image" src="${imageSrc}" alt="${heroEvent.name}" onclick="openLightbox(this.src)" style="cursor: pointer;" fetchpriority="high" width="600" height="800">
                    </div>
                    <div class="hero-event__content">
                        <span class="hero-event__badge" id="hero-event-badge">${categoryLabel}</span>
                        <h1 class="hero-event__title" id="hero-event-title">${heroEvent.name}</h1>
                        <div class="hero-event__meta">
                            <div class="hero-event__meta-item">
                                <span>📅</span>
                                <span id="hero-event-date">${dateFormatted}</span>
                            </div>
                            <div class="hero-event__meta-item">
                                <span>🕐</span>
                                <span id="hero-event-time">${heroEvent.time}</span>
                            </div>
                            <div class="hero-event__meta-item">
                                <span>📍</span>
                                <span id="hero-event-location">${locationHtml}</span>
                            </div>
                        </div>
                        <div class="hero-event__description" id="hero-event-description">${description}</div>
                        <div class="hero-event__actions" id="hero-event-actions">${actionsHtml}</div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Filter`;

    html = html.replace(heroSectionRegex, preRenderedHero);

    // Write back
    fs.writeFileSync(indexPath, html, 'utf8');
    console.log(`  ✓ Hero pre-rendered: "${heroEvent.name}"`);
    console.log(`  ✓ Preload added: ${imageSrc}\n`);
}

function createGoogleCalendarLink(event) {
    const startDate = new Date(`${event.date}T${event.time}`);
    const endDate = new Date(startDate.getTime() + 2 * 60 * 60 * 1000);
    const encodedName = encodeURIComponent(event.name);
    const encodedDescription = encodeURIComponent(stripHtml(event.description || ''));
    const encodedLocation = encodeURIComponent(event.locationForCalendar || event.location);
    return `https://www.google.com/calendar/render?action=TEMPLATE&text=${encodedName}&dates=${startDate.toISOString().replace(/-|:|\.\d\d\d/g, '')}/${endDate.toISOString().replace(/-|:|\.\d\d\d/g, '')}&details=${encodedDescription}&location=${encodedLocation}`;
}

/**
 * Generate event page HTML
 */
function generateEventPage(event) {
    const eventUrl = `${SITE_URL}/events/${event.id}/`;
    const imageUrl = event.image ? `${SITE_URL}/${event.image}` : `${SITE_URL}/img/og-image.webp`;
    const categoryLabel = categoryLabels[event.category] || 'Подія';
    const description = stripHtml(event.description || '');
    const startDateTime = formatDateISO(event.date, event.time);
    const endDateTime = formatDateISO(event.date,
        `${(parseInt(event.time.split(':')[0]) + 2).toString().padStart(2, '0')}:${event.time.split(':')[1]}`);

    return `<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${event.name} | У Стендап</title>
    <meta name="description" content="${description}">
    <meta name="robots" content="index, follow">
    <link rel="canonical" href="${eventUrl}">
    <meta property="og:type" content="event">
    <meta property="og:url" content="${eventUrl}">
    <meta property="og:title" content="${event.name}">
    <meta property="og:description" content="${description}">
    <meta property="og:image" content="${imageUrl}">
    <meta property="og:locale" content="uk_UA">
    <meta property="event:start_time" content="${startDateTime}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${event.name}">
    <meta name="twitter:description" content="${description}">
    <meta name="twitter:image" content="${imageUrl}">
    <meta name="geo.region" content="DE-NW">
    <meta name="geo.placename" content="Köln">
    <link rel="icon" type="image/svg+xml" href="/img/favicon.svg">
    <link rel="stylesheet" href="/css/style.css">
    <style>
        .event-page { padding: 2rem 0; }
        .event-page__header { margin-bottom: 2rem; }
        .event-page__category { display: inline-block; padding: 0.25rem 0.75rem; background: var(--color-accent); color: var(--color-primary); border-radius: var(--radius-sm); font-size: 0.85rem; font-weight: 600; margin-bottom: 0.5rem; }
        .event-page__title { font-size: 2rem; font-weight: 700; color: var(--color-primary); margin-bottom: 1rem; }
        .event-page__meta { display: flex; flex-wrap: wrap; gap: 1.5rem; margin-bottom: 2rem; font-size: 1.1rem; }
        .event-page__meta-item { display: flex; align-items: center; gap: 0.5rem; }
        .event-page__image { width: 100%; max-width: 600px; border-radius: var(--radius-lg); margin-bottom: 2rem; cursor: pointer; }
        .event-page__description { font-size: 1.1rem; line-height: 1.8; white-space: pre-line; margin-bottom: 2rem; }
        .event-page__actions { display: flex; flex-wrap: wrap; gap: 1rem; margin-bottom: 3rem; }
        .event-page__back { margin-top: 2rem; }
        .lightbox { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.9); z-index: 9999; cursor: pointer; justify-content: center; align-items: center; }
        .lightbox.active { display: flex; }
        .lightbox img { max-width: 90%; max-height: 90%; object-fit: contain; }
        .lightbox__close { position: absolute; top: 20px; right: 30px; color: white; font-size: 2rem; cursor: pointer; }
        @media (min-width: 768px) { .event-page__title { font-size: 2.5rem; } }
    </style>
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Event",
        "name": "${event.name.replace(/"/g, '\\"')}",
        "description": "${description.replace(/"/g, '\\"')}",
        "startDate": "${startDateTime}",
        "endDate": "${endDateTime}",
        "eventStatus": "https://schema.org/EventScheduled",
        "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
        "location": {
            "@type": "Place",
            "name": "${(event.location || '').replace(/"/g, '\\"')}",
            "address": { "@type": "PostalAddress", "streetAddress": "${(event.locationForCalendar || event.location || '').replace(/"/g, '\\"')}", "addressLocality": "Köln", "addressCountry": "DE" }
        },
        "organizer": { "@type": "Organization", "name": "У Стендап", "url": "${SITE_URL}" },
        "image": "${imageUrl}"${event.ticketLink ? `, "offers": { "@type": "Offer", "url": "${event.ticketLink}", "availability": "https://schema.org/InStock" }` : ''}
    }
    </script>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="container">
                <a class="navbar-brand" href="/"><img src="/img/logo.webp" alt="У Стендап" width="120" height="50"><span class="brand-tagline">український стендап у Кельні</span></a>
                <button class="navbar-toggler" type="button" aria-label="Toggle navigation" onclick="toggleMenu()"><span></span><span></span><span></span></button>
                <div class="navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="/">Головна</a></li>
                        <li class="nav-item"><a class="nav-link active" href="/all-events.html">Всі події</a></li>
                        <li class="nav-item"><a class="nav-link" href="/#about-us">Про нас</a></li>
                        <li class="nav-item"><a class="nav-link" href="/other-clubs.html">Інші клуби</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <article class="event-page">
        <div class="container">
            <div class="event-page__header">
                <span class="event-page__category">${categoryLabel}</span>
                <h1 class="event-page__title">${event.name}</h1>
                <div class="event-page__meta">
                    <div class="event-page__meta-item"><strong>📅</strong> ${formatDate(event.date)}</div>
                    <div class="event-page__meta-item"><strong>🕐</strong> ${event.time}</div>
                    <div class="event-page__meta-item"><strong>📍</strong> ${event.linkToMaps ? `<a href="${event.linkToMaps}" target="_blank" rel="noopener">${event.location}</a>` : event.location}</div>
                </div>
            </div>
            ${event.image ? `<img src="/${event.image}" alt="${event.name}" class="event-page__image" onclick="openLightbox(this.src)">` : ''}
            <div class="event-page__description">${event.description || ''}</div>
            <div class="event-page__actions">
                ${event.ticketLink ? `<a href="${event.ticketLink}" target="_blank" class="btn btn-primary btn-lg">Купити квитки</a>` : ''}
                <a href="${createGoogleCalendarLink(event)}" target="_blank" class="btn btn-outline-secondary">Google Calendar</a>
                <button onclick="generateICS()" class="btn btn-outline-secondary">Apple Calendar</button>
            </div>
            <a href="/" class="event-page__back">← Назад до всіх подій</a>
        </div>
    </article>
    <div class="lightbox" id="lightbox" onclick="closeLightbox()"><span class="lightbox__close">×</span><img src="" alt="" id="lightbox-img"></div>
    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-info"><p class="footer-copyright">© ${new Date().getFullYear()} У Стендап. Усі права захищені.</p><p class="footer-location">Köln, Deutschland</p></div>
                <div class="footer-social">
                    <a href="https://www.instagram.com/u_standup_cologne/" target="_blank" rel="noopener"><img src="/img/instagram-icon.svg" alt="Instagram" width="32" height="32"></a>
                    <a href="https://chat.whatsapp.com/BXBNeksXPrJ29btgeo9BZZ" target="_blank" rel="noopener"><img src="/img/whatsapp-icon.svg" alt="WhatsApp" width="32" height="32"></a>
                </div>
            </div>
        </div>
    </footer>
    <script src="/ics-browserified.js"></script>
    <script>
        function toggleMenu() { const nav = document.getElementById('navbarNav'); if (nav) nav.classList.toggle('show'); }
        function openLightbox(src) { document.getElementById('lightbox-img').src = src; document.getElementById('lightbox').classList.add('active'); document.body.style.overflow = 'hidden'; }
        function closeLightbox() { document.getElementById('lightbox').classList.remove('active'); document.body.style.overflow = ''; }
        document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeLightbox(); });
        function generateICS() {
            const event = ${JSON.stringify({ id: event.id, name: event.name, date: event.date, time: event.time, description: stripHtml(event.description || ''), location: event.locationForCalendar || event.location, linkToMaps: event.linkToMaps })};
            const startDate = new Date(event.date + 'T' + event.time);
            window.ics.createEvent({ start: [startDate.getFullYear(), startDate.getMonth() + 1, startDate.getDate(), startDate.getHours(), startDate.getMinutes()], duration: { hours: 2 }, title: event.name, description: event.description, location: event.location, url: event.linkToMaps, status: 'CONFIRMED', busyStatus: 'BUSY', productId: 'u-standup/ics', alarms: [{ action: 'display', trigger: { hours: 2, before: true } }] }, (error, value) => {
                if (error) { console.error(error); return; }
                const blob = new Blob([value], { type: 'text/calendar;charset=utf-8' });
                const link = document.createElement('a'); link.href = window.URL.createObjectURL(blob); link.download = event.name + '.ics'; link.click();
            });
        }
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "e9e3d01d906d4f06946bb1f72ba15410"}'></script>
    <script src="/js/analytics.js"></script>
</body>
</html>`;
}

/**
 * Build event detail pages
 */
function buildEventPages(events) {
    console.log('Building event pages...');

    const eventsDir = path.join(DIST_DIR, 'events');
    fs.mkdirSync(eventsDir, { recursive: true });

    for (const event of events) {
        const eventDir = path.join(eventsDir, event.id);
        fs.mkdirSync(eventDir, { recursive: true });

        const html = generateEventPage(event);
        fs.writeFileSync(path.join(eventDir, 'index.html'), html, 'utf8');
        console.log(`  ✓ events/${event.id}/`);
    }

    console.log(`\nGenerated ${events.length} event pages\n`);
}

/**
 * Generate sitemap.xml
 */
function generateSitemap(events) {
    console.log('Generating sitemap.xml...');

    const today = new Date().toISOString().split('T')[0];
    const now = new Date();

    const upcomingEvents = events.filter(e => new Date(`${e.date}T${e.time}`) >= now);
    const pastEvents = events.filter(e => new Date(`${e.date}T${e.time}`) < now);

    let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url><loc>${SITE_URL}/</loc><lastmod>${today}</lastmod><changefreq>weekly</changefreq><priority>1.0</priority></url>
    <url><loc>${SITE_URL}/all-events.html</loc><lastmod>${today}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>
    <url><loc>${SITE_URL}/other-clubs.html</loc><lastmod>${today}</lastmod><changefreq>monthly</changefreq><priority>0.6</priority></url>
`;

    for (const event of upcomingEvents) {
        sitemap += `    <url><loc>${SITE_URL}/events/${event.id}/</loc><lastmod>${today}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>\n`;
    }

    for (const event of pastEvents) {
        sitemap += `    <url><loc>${SITE_URL}/events/${event.id}/</loc><lastmod>${today}</lastmod><changefreq>yearly</changefreq><priority>0.4</priority></url>\n`;
    }

    sitemap += `    <url><loc>${SITE_URL}/data/events.json</loc><lastmod>${today}</lastmod><changefreq>weekly</changefreq><priority>0.5</priority></url>
</urlset>`;

    fs.writeFileSync(path.join(DIST_DIR, 'sitemap.xml'), sitemap, 'utf8');
    console.log('✓ sitemap.xml\n');
}

/**
 * Main build function
 */
async function build() {
    console.log('=== Building dist/ for deployment ===\n');

    cleanDist();
    copyStaticFiles();
    await optimizeImages();
    const events = buildEvents();
    preRenderHeroSection(events);
    buildEventPages(events);
    generateSitemap(events);

    console.log('=== Build complete! ===');
    console.log(`Output: ${DIST_DIR}`);
}

build().catch(console.error);
